login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.login, name='login'),
    path('lists/', views.lists, name='lists'),
    path('lists/<int:user_account_id>/',views.detail, name='detail'),
    path('profile/',views.profile, name='profile'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('login/', include('login.urls')),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),

    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),

]

login/models.py
from django.db import models

# Create your models here.
class UserAccount(models.Model):
    user_name = models.CharField(max_length=40)
    user_password = models.CharField(max_length=20)

    def __str__(self):
        return self.user_name+self.user_password

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

login/views.py
from django.shortcuts import get_object_or_404,render, render_to_response
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader

from .models import UserAccount

# Create your views here.

# def login(request):
#     html_str = "view: login"
#     return HttpResponse(html_str)

def login(request):
    # template = loader.get_template('login/login.html')
    return render(request, 'login/login.html')


# def lists(request):
#     html_str = "view: lists"
#     return HttpResponse(html_str)


def lists(request):
    user_account_list = UserAccount.objects.order_by('user_name')[:]
    template = loader.get_template('login/list.html')
    context = {
        'user_account_list': user_account_list,
    }
    return HttpResponse(template.render(context, request))


def detail(request, user_account_id):
    user_account = get_object_or_404(UserAccount, pk=user_account_id)
    return render(request, 'login/detail.html', {'user_account': user_account})


def profile(request):
    # user_account = get_object_or_404(UserAccount, pk=user_account_id)
    context = {}

    if request.POST:
        context['input_username'] = request.POST['userName']
        context['input_userpassword'] = request.POST['userPassword']
    else:
        return HttpResponse("Invalid")

    # template = loader.get_template('login/profile.html')
    return render_to_response('login/profile.html', context)
    

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.http import Http404
from django.urls import reverse

# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect

from .models import Question, Choice

# def index(request):
#     html_str = r"<!doctype html><html><head><title>Polls</title></head><body><h1>My First App Polls</h1><div><p>test this web page<br/>Hello, world. You're at the polls index.</p><img src='https://thumbs.dreamstime.com/z/assassin-outlaw-thief-burglar-fantasy-medieval-action-rpg-game-character-layered-animation-ready-vector-illustration-131042596.jpg' width='20%'/></div></body></html>"

#     img_path= r"https://thumbs.dreamstime.com/z/assassin-outlaw-thief-burglar-fantasy-medieval-action-rpg-game-character-layered-animation-ready-vector-illustration-131042596.jpg"

#     return HttpResponse(html_str)

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))

# def detail(request, question_id):
#    return HttpResponse("You're looking at question %s." % question_id)


# def detail(request, question_id):
#     try:
#         question = Question.objects.get(pk=question_id)
#     except Question.DoesNotExist:
#         raise Http404("Question does not exist")
#     return render(request, 'polls/detail.html', {'question': question})


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)


# def vote(request, question_id):
#     return HttpResponse("You're voting on question %s." % question_id)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))



# def results(request, question_id):
#     response = "You're looking at the results of question %s."
#     return HttpResponse(response % question_id)

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

login/templates/login/detail.html
<!DOCTYPE html>
<html>
<head>
    <title>User Account Detail</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}">
</head>
<h1>User Account Detail</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

{% csrf_token %}

    User Name: {{user_account.user_name}}<br/>
    User Password: {{user_account.user_password}}<br/>


<a href="{% url 'login:lists' %}">back to user list</a>

login/templates/login/list.html
<!DOCTYPE html>
<html>
<head>
    <title>User Account List</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}">
</head>

<body>
{% if user_account_list %}
    <ul>
    {% for user_account in user_account_list %}
        
        <li><a href="{% url 'login:detail' user_account.id %}">{{ user_account.user_name }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>No users are available.</p>

{% endif %}

</body>
</html>

login/templates/login/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}">
</head>

<body>
    <div id="top">
        &nbsp; 
    </div>

    <div id="head">
        Welcome to My Website
    </div>

    <div id="loginform">
        <form action="{% url 'login:profile' %}" method="POST">
            {% csrf_token %}
            <table>
                <tr>
                    <td>Username&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td><input type="text" id="userName" name="userName" value="" placeholder=""/></td>
                </tr>
                <tr>
                    <td>Password&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td><input type="text" id="userPassword" name="userPassword" value="" placeholder=""/></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <br/>
                        <input type="submit" value="Sign in" id="btn_signin"/>
                    </td>
                </tr>
            </table>  
            
        </form>
    </div>

</body>
</html>

login/templates/login/profile.html
<!DOCTYPE html>
<html>
<head>
    <title>User Profile</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login/style.css' %}">
</head>

<body>

<h2>Welcome {{input_username}}</h2>
<hr/>
<p>Your profile is</p>
{{input_username}} <br/>
{{input_userpassword}}



</body>
</html>

polls/templates/polls/detail.html
<!--
>>>>>>> e00851f4d4c91a380696df66f81856db26ec8576
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>


<hr/>-->


<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">

</form>

<a href="{% url 'polls:index' %}">back to question list</a>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>

{% endif %}

</body>
</html>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>